### ISSUE TITLE
Unsure of usage

### ISSUE THREAD

**Issue by NickDevoctomy** [LuukEbenau/SacaDev.Muse#7]
Hi there,

Sorry for the stupid question but after reading the instructions and attempting connection with my Muse I'm not getting anything, so not sure I understand how to connect.

My Muse is paired to the computer via bluetooth.  I'm running the test Cli and that simply outputs "Hello World!" but then does nothing else.

`var muse = manager.Connect("jantje", 7000);`

What's that line referring to port 7000? I must be missing something important.  Thanks for your time.

**Comment by LuukEbenau** [comment]
The second parameter is referring to port 7000, change this to the port you are using in your app on your pc. in case you don't have the muse app on your pc, then this is likely the issue. The package is not directly reading bluetooth data but instead makes uses of the official muse connect application as a broker.

Hope this resolves any questions!
